spring:
  application:
    name: smartshop
  datasource:
    url: jdbc:postgresql://localhost:5432/smartshop
    username: postgres
    password: ADMIN
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml

# Configuration Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    default-models-expand-depth: 1
    default-model-expand-depth: 1
